import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideBar from "@/components/Sidebar";
import { RiBarChart2Fill } from "react-icons/ri";
import { IoChatboxSharp } from "react-icons/io5";

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistMono.className}`}>
        <SideBar
          links={[
            {
              name: "Dashboard",
              icon: <RiBarChart2Fill />,
            },
            {
              name: "Chat",
              icon: <IoChatboxSharp />,
            },
          ]}
        />
        <div className="bg-[#F6F6F6] w-[85vw] h-[100vh] right-0 absolute">
          {children}
        </div>
      </body>
    </html>
  );
}
